### PR TITLE
Adding immediate processing

### PR DESCRIPTION
**Pull request by jc00ke**
Works in jruby 1.6.2, MRI 1.9.2 & rbx 2.0.0pre. The only thing that's a little jacked up is that if you run `rake test` the immediate tests will fail. But if you run that file by itself it will pass (it's the global var $queue_work's fault) and so will running test/test_batch.rb & test/test_girl_friday.rb

I'm not a fan of the global but it's the simplest way to set var to be checked. I started down a class attr for a bit but it didn't get me anywhere.

### CODE REVIEW

**Comment by mperham** [comment]
I don't like like the global approach at all.  I would suggest rather than changing the definition of push, just put an early exit clause in push:

```
def push(msg, &block)
  return process_immediately(msg, &block) if GirlFriday.immediate?
  ...
end
```

and just have your test code toggle the immediate flag.

**Comment by jc00ke** [comment]
Cool, thanks for the feedback. I will go down that road & submit another pull request.

**Comment by mperham** [comment]
Alternatively, we could just document how to do this using flexmock.  See my most recent commit.

**Comment by jc00ke** [comment]
Yeah, though if we do it in a general way then those of us that don't use flexmock can still enjoy ;-)

**Comment by mperham** [comment]
I don't think it can be done in mocha.  I couldn't figure out how to do it in 10 minutes of investigation.

I'm leaning towards GirlFriday.immediate! which would simply alias :<< and :push to a new method, :push_immediate.  Call it once at the top of your test helper and you're good to go.

**Comment by jc00ke** [comment]
I think that would be ideal. You want to do it or would you like me to?
Sounds like you have a specific way you want it done, so I'm happy to bow
out.

**Comment by mperham** [comment]
I'd prefer you to do it so you'll get commit credit.  I'll clean up any lingering issues once you are done.  Remember to give yourself credit in the changelog.

**Comment by jc00ke** [comment]
Cool, I'll get on it.

**Pull request closed without merging**
