### PR TITLE
Use fakeredis for tests

### PR DESCRIPTION
**Pull request by guilleiguaran**

### CODE REVIEW

**Comment by mperham** [comment]
Seems reasonable.  I'm not a huge fan of requiring a live Redis instance to run the tests as long as this gives the equivalent code coverage.  @jc00ke?

**Comment by jc00ke** [comment]
I suppose... I don't mind making Redis available for a few reasons though
1. It's available on Travis, which at some point should be the canonical "it's green" reporter
2. Redis will probably be used by a good percentage of people, since they most likely don't want to risk jobs being deleted should their app die (jeez, probably... most likely... like I know what I'm talking about)
3. I've been toying with the idea of adding more backends... Riak, Mongo, etc. Do we have fake versions of these too, or would testing against a running server be necessary?
4. What about splitting the Redis store out into a separate gem? Might we handle any new stores the same way?

**Comment by mperham** [comment]
Rails' current fascination with breaking out abstractions into little gems has me reluctant to sign off on separate gems.  I want to keep girl_friday simple and opinionated.  Redis has simple queue operations, which is exactly what we need.

At the same time, if you are using girl_friday, you probably should be running redis locally and speed is really not a problem.  So I think this pull request is unnecessary.  Alternative opinions, please speak up.

**Comment by jc00ke** [comment]
Works for me, though how would you like to handle other storage backends besides Redis?

**Comment by mperham** [comment]
Add them to examples for now as an example of alternative persistence options.  We can move it to lib when/if we want to officially support it.

**Comment by jc00ke** [comment]
Ah, good idea. Thx.

**Pull request closed without merging**
