### PR TITLE
fix alias bug (should be alias_method to avoid runtime error)

### PR DESCRIPTION
**Pull request by ryanlecompte**
whoops, a little bug snuck into last night's release:

this will generate a runtime error when we're in Rails dev environment (alias doesn't want commas):

alias :push_async, :push_immediately

the pull request switches this to use alias_method instead.

thanks!

ryan

### CODE REVIEW

**Comment by mperham** [comment]
Would you add a test so this doesn't break in the future?

**Comment by ryanlecompte** [comment]
Yep! Will do right now.

Thanks!

Ryan

**Comment by ryanlecompte** [comment]
Mike, I just added a new test to verify that we process items immediately when Rails environment is present. I didn't want to load the whole Rails environment for the tests, so I instead fake a Rails environment for the unit test. Please take a look when you get a chance.

Thanks!

**Comment by mperham** [comment]
That's some impressively hardcore Ruby.  I wonder if there's an easier way to refactor the whole thing so we don't have to use so much magic but at least we have a test.

**Comment by ryanlecompte** [comment]
Yeah, there's definitely a way to make it a bit less hardcore'ish, lol. :-)
We could wrap the whole defined?(Rails) logic in a class method on
WorkQueue, and just invoke it as the class is being defined. Later, from the
test, we can just invoke that class method again and it would dynamically
re-define the #push_async definition and aliases. I figured I'd just do the
magic in the test as opposed to restructuring WorkQueue again for the
release.

Thanks for taking a look!

Ryan

**Pull request merged**
