### PR TITLE
Update connection pool dependency

### PR DESCRIPTION
**Pull request by sferik**
As indicated by the branch name, this pull request started as a simple update to the `connection_pool` dependency but then I continued to make a few additional changes. Everything is in atomic commits so feel free to take what you like and leave what you don't. A few of the changes (e.g. alphabetical gemspec) are purely a matter of taste.

I also added `Bundler::GemHelper.install_tasks` to the `Rakefile`. Again, it's a matter of taste, but it makes building and tagging releases easier and I couldn't think of any reason not to add it.

Once you merge in the `connection_pool` dependency update, please ship a new release of this gem. Thanks!

### CODE REVIEW

**Comment by jc00ke** [comment]
:+1:

**Comment by jc00ke** [comment]
[Released](http://rubygems.org/gems/girl_friday/versions/0.11.2)

**Comment by sferik** [comment]
Thanks for the quick turnaround!

**Comment by jc00ke** [comment]
Gotta do something productive while I cook my oatmeal :wink:

**Pull request merged**
