### PR TITLE
Rubinius change does incorrect require, causing name clash

### PR DESCRIPTION
**Pull request by barttenbrinke**
We are using an actor.rb class in our project, which gets required, causing all kinds of nastyness. Also I'm not really sure what you are trying to do here. You should just require both without the error catching and everything should work fine.

### CODE REVIEW

**Comment by jc00ke** [comment]
We want to use the Rubinius actor if possible because it's specially suited for Rubinius, using the `Rubinius::Channel`. Can you require your `actor.rb` using a specific path to avoid this issue?

Is `actor.rb` a model in your app?

**Comment by barttenbrinke** [comment]
Yes, actor.rb is a model in my app. But where are you trying to require the Rubinius actor from? A gem should interfere with the objectspace at little as possible imho.

**Comment by jc00ke** [comment]
It's not a gem, it's included in Rubinius. `lib/actor.rb` based on mentalguy's Ruby implementation of the Actor pattern.

With Rubinius I guess you can consider `actor` a reserved word of sorts. It is probably best to file an issue over there, but I doubt they will change anything. Maybe they have another solution though.

**Comment by mperham** [comment]
Unfortunately you will need to rename or namespace your model to work with girl_friday.  Actor is a reserved top-level class name in Rubinius and we're using its actor implementation.

**Comment by jc00ke** [comment]
Oops, didn't mean to reopen.

I'm going to try the actor gem for #61.

**Pull request closed without merging**
